CREATE TABLE CABLE_PROPERTIES(
PROP_ID INTEGER NOT NULL PRIMARY KEY,
PROPERTY_INFO VARCHAR(50) NOT NULL);

CREATE GENERATOR PROP_ID_GEN;

CREATE TRIGGER TRG_PROP_ID_GEN FOR CABLE_PROPERTIES
ACTIVE BEFORE INSERT
AS
BEGIN
	IF (NEW.PROP_ID IS NULL) THEN
    NEW.PROP_ID = GEN_ID(PROP_ID_GEN, 1);
END;

INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Индивидуальный экран, фольга');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Индивидуальный экран, оплётка');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Общий экран, фольга');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Общий экран, оплётка');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Наличие заполнения');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Проволочная броня');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Ленточная броня');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Наличие шланга поверх брони');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Наличие водоблокирующей ленты');
INSERT INTO CABLE_PROPERTIES (PROPERTY_INFO) VALUES ('Кабель для искробезопасных цепей');


CREATE TABLE LIST_CABLE_PROPERTIES(
LIST_ID INTEGER NOT NULL PRIMARY KEY,
CABLE_ID INTEGER NOT NULL,
PROP_ID INTEGER NOT NULL);

CREATE GENERATOR LIST_PROP_ID_GEN;

CREATE TRIGGER TRG_LIST_PROP_ID_GEN FOR LIST_CABLE_PROPERTIES
ACTIVE BEFORE INSERT
AS
BEGIN
	IF (NEW.LIST_ID IS NULL) THEN
    NEW.LIST_ID = GEN_ID(LIST_PROP_ID_GEN, 1);
END;

ALTER TABLE LIST_CABLE_PROPERTIES
ADD CONSTRAINT FK_CABLE_ID_LIST_PROP FOREIGN KEY (CABLE_ID) REFERENCES CABLE (CABLE_ID) ON UPDATE CASCADE;

ALTER TABLE LIST_CABLE_PROPERTIES
ADD CONSTRAINT FK_PROP_ID_LIST_PROP FOREIGN KEY (PROP_ID) REFERENCES CABLE_PROPERTIES (PROP_ID) ON UPDATE CASCADE;

ALTER TABLE CABLE
ADD FULL_NAME VARCHAR(50) NOT NULL;