SELECT
	csn.SHORT_NAME, pg.DESIGNATION_IN_CABLE_TITLE, fpc.DESIGNATION, cb.ELEMENTS_COUNT, c.AREA_IN_SQR_MM,
	pwcs.COLOR_SCHEME, cb.MAX_COVER_DIAMETER
FROM CABLE cb

JOIN FIRE_PROTECTION_CLASS fpc ON cb.FIRE_PROTECT_ID = fpc.FIRE_PROTECT_ID
JOIN INSULATED_BILLET ib ON cb.BILLET_ID = ib.INS_BILLET_ID
JOIN CONDUCTOR c ON c.COND_ID = ib.COND_ID
JOIN CABLE_SHORT_NAME csn ON ib.SHRT_N_ID = csn.SHRT_N_ID 
JOIN POLYMER_GROUP pg ON cb.COVER_POLYMER_GROUP_ID = pg.P_GROUP_ID 

JOIN LIST_CABLE_POWER_COLOR lcpc ON lcpc.CABLE_ID = cb.CABLE_ID 
JOIN POWER_WIRES_COLOR_SCHEME pwcs ON pwcs.PWR_COLOR_SCHEME_ID = lcpc.POWER_COLOR_SCHEME_ID 

LEFT JOIN LIST_CABLE_PROPERTIES lcp ON lcp.CABLE_ID = cb.CABLE_ID 

WHERE
	c.AREA_IN_SQR_MM = 1.0
ORDER BY fpc.DESIGNATION, cb.ELEMENTS_COUNT, pg.DESIGNATION_IN_CABLE_TITLE;


SELECT 
	csn.SHORT_NAME, pg.DESIGNATION_IN_CABLE_TITLE, fpc.DESIGNATION, c.ELEMENTS_COUNT,
	cnd.AREA_IN_SQR_MM, pwcs.COLOR_SCHEME, c.MAX_COVER_DIAMETER, cp.PROPERTY_INFO 
FROM LIST_CABLE_PROPERTIES lcp 

JOIN CABLE c ON c.CABLE_ID = lcp.CABLE_ID
JOIN CABLE_PROPERTIES cp ON cp.PROP_ID = lcp.PROP_ID
JOIN FIRE_PROTECTION_CLASS fpc ON c.FIRE_PROTECT_ID = fpc.FIRE_PROTECT_ID
JOIN INSULATED_BILLET ib ON c.BILLET_ID = ib.INS_BILLET_ID
JOIN CONDUCTOR cnd ON cnd.COND_ID = ib.COND_ID
JOIN CABLE_SHORT_NAME csn ON ib.SHRT_N_ID = csn.SHRT_N_ID
JOIN POLYMER_GROUP pg ON c.COVER_POLYMER_GROUP_ID = pg.P_GROUP_ID
JOIN LIST_CABLE_POWER_COLOR lcpc ON lcpc.CABLE_ID = c.CABLE_ID 
JOIN POWER_WIRES_COLOR_SCHEME pwcs ON pwcs.PWR_COLOR_SCHEME_ID = lcpc.POWER_COLOR_SCHEME_ID 

WHERE
	csn.SHORT_NAME = 'КУНРС' AND
	c.ELEMENTS_COUNT = 4 AND
	pg.POLYMER_GROUP = 'HFCompound' AND
	cnd.AREA_IN_SQR_MM = 0.75
	
ORDER BY pwcs.COLOR_SCHEME, c.MAX_COVER_DIAMETER;


SELECT csn.SHORT_NAME, pg.DESIGNATION_IN_CABLE_TITLE, fpc.DESIGNATION, c.ELEMENTS_COUNT,
	cnd.AREA_IN_SQR_MM, --pwcs.COLOR_SCHEME,
	c.MAX_COVER_DIAMETER, cp.PROPERTY_INFO 
FROM LIST_CABLE_PROPERTIES lcp, CABLE c, CABLE_PROPERTIES cp 

JOIN FIRE_PROTECTION_CLASS fpc ON c.FIRE_PROTECT_ID = fpc.FIRE_PROTECT_ID
JOIN INSULATED_BILLET ib ON c.BILLET_ID = ib.INS_BILLET_ID
JOIN CONDUCTOR cnd ON cnd.COND_ID = ib.COND_ID
JOIN CABLE_SHORT_NAME csn ON ib.SHRT_N_ID = csn.SHRT_N_ID
JOIN POLYMER_GROUP pg ON c.COVER_POLYMER_GROUP_ID = pg.P_GROUP_ID
--JOIN LIST_CABLE_POWER_COLOR lcpc ON lcpc.CABLE_ID = c.CABLE_ID 
--JOIN POWER_WIRES_COLOR_SCHEME pwcs ON pwcs.PWR_COLOR_SCHEME_ID = lcpc.POWER_COLOR_SCHEME_ID 

WHERE
	c.MAX_COVER_DIAMETER < 11.5 AND
	c.CABLE_ID = lcp.CABLE_ID AND
	cp.PROP_ID = lcp.PROP_ID AND
	--csn.SHORT_NAME = 'СКАБ 250' AND
	c.ELEMENTS_COUNT = 4 AND
	pg.POLYMER_GROUP = 'HFCompound' AND
	cnd.AREA_IN_SQR_MM = 1.5
	
ORDER BY --pwcs.COLOR_SCHEME, 
c.MAX_COVER_DIAMETER;